name: andylamrock
favicon: null
layout_spectrum: 0.38609675224870443
typography_spectrum: 0.1472332172561437
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#00acdb'
    - '#bae9f5'
    - '#52c9e7'
    - '#54aed4'
  brandStrength: 0.4790106094442308
  lightness: 0.8794333571568131
  saturation: 0.8674723776057363
  rhythmicContrast: 0.3812237505335361
purpose: []
